#### general settings
name: EDVR
use_tb_logger: true
model: video_base
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: EDVR
    mode: Vimeo90K
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot: ../data/REDS/train
    cache_keys: ~
    filelist: ../data/REDS/train/groups.txt
    N_frames: 5
    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 8
    GT_size: 128
    LQ_size: 128
    augment: true
    color: RGB
  val:
    name: EDVR
    mode: video_test
    n_workers: 0
    filelist: ../data/REDS/val/groups.txt
    cache_data: ~
    batch_size: 1
    use_shuffle: false

#### network structures
network_G:
  which_model_G: EDVR
  nf: 32
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: false
  HR_in: false
  w_TSA: true

#### path
path:
  root: output
  results_root: output
  pretrain_model_G: pretrained/EDVR_L_deblur_REDS_official-ca46bd8c.pth
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600001
  ft_tsa_only: ~
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 150000, 150000, 150000]
  restarts: [150000, 300000, 450000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 5e-6

  pixel_criterion: cb
  pixel_weight: 1.0
#  ssim_weight: 1000.0
  val_freq: !!float 7000

  manual_seed: 0

#### logger
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 10000
